### ISSUE TITLE
Issues to fix before Corral can replace Stable

### ISSUE THREAD

**Issue by cquinn** [ponylang/corral#69]
This is a master list of issues that should be addressed in order for Corral to meet feature parity and be able to replace Stable.

Must-haves:
* [x] #26 Must support simple tag / branch references
* [x] #32 Remote GitLab & Bitbucket support
* [x] #33 Local git repos
* [x] #34 Local bundles (w/o vcs)
* [x] #59 Update recursion is a must-have, master lock is a should-have
* [ ] #55 Windows builds

Should-haves:
* [x] #7 Should have at least simple usage info in a howto
* [x] #27 The -n option will help people learn how Corral works
* [ ] #28 It might be messy to move the repo cache later.
* [x] #62 Don't want recursion crashes.

**Comment by cquinn** [comment]
Closing this list now in favor of using milestone#1
